### ISSUE TITLE
Adding module with task throws NullPointerException, though app still works fine

### ISSUE THREAD

**Issue by chanckben** [AY1920S2-CS2103T-W13-3/main#274]
When I try to add a new module with a task to the current semester (with or without a deadline), a NullPointerException is thrown, as shown in the stack trace below.

![image](https://user-images.githubusercontent.com/42468533/78549458-0292db00-7835-11ea-872d-82fe63834d39.png)

Can go to the relevant classes to check what's the issue. The app still works fine, but it might cause more bugs later, so best to fix this.

**Comment by jadetayy** [comment]
added a new condition in addcommand under add deadlines to add module FIRST before proceeding to other conditions
