### ISSUE TITLE
NullPointerException on adding Deadline

### ISSUE THREAD

**Issue by gyant6** [AY1920S2-CS2103T-W13-3/main#315]
Adding deadline feature is now broken

Try 
1. Create a new profile
2. Add a task to current semester

Might be because of the way the module code is stored

BEFORE:
<img width="496" alt="pic1" src="https://user-images.githubusercontent.com/45054750/79041247-de624000-7c20-11ea-8b61-423e273fadff.PNG">

After:
<img width="219" alt="pic2" src="https://user-images.githubusercontent.com/45054750/79041277-18334680-7c21-11ea-98c0-076da40bb6ea.PNG">

**Comment by chanckben** [comment]
Fixed in the above PR
